### ISSUE TITLE
Update for Python 3.8+

### ISSUE THREAD

**Issue by MatthewTingum** [MatthewTingum/hpsrec#2]
Initial attempt to run gives the following error:
```sh
$ ./pysrec 
./pysrec:42: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if end is 0:
Traceback (most recent call last):
  File "./pysrec", line 10, in <module>
    from zwuenf.pysrec.SRecord import SRecord
  File "/home/user/Documents/hpx/hpsrec/zwuenf/pysrec/SRecord.py", line 7, in <module>
    from colored import fore, style
ModuleNotFoundError: No module named 'colored'
```

**Comment by MatthewTingum** [comment]
Closing. Glossed over the error message.

**Comment by MatthewTingum** [comment]
Error with dependencies installed:
```sh
$ ./pysrec 
./pysrec:42: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if end is 0:
Usage: pysrec [OPTIONS] COMMAND [ARGS]...

  Command line interface for pysrec. Use --help for details.

Options:
  --help  Show this message and exit.

Commands:
  binary  Generate a binary file from a Motorola S-Record file.
  cat     Print Motorola S-record file.
  check   Check a Motorola S-Record file.
  info    Show information about a Motorola S-Record file.
```
